name: pro_multimedia
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  injectable: ^2.4.2
  retrofit: ^4.4.1
  json_serializable: ^6.1.4
  freezed_annotation: ^2.1.0
  get_it: ^8.0.2
  dartz: ^0.10.1
  dio: ^5.7.0
  json_annotation: ^4.8.0
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^2.6.1
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/videos/
